# Generated by Django 4.2.29 on 2026-03-05 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='master',
            options={'verbose_name': 'Самозанятый мастер', 'verbose_name_plural': 'Самозанятые мастера'},
        ),
        migrations.RemoveField(
            model_name='master',
            name='salon_name',
        ),
        migrations.AddField(
            model_name='master',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='master',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Фамилия'),
        ),
    ]
