# Generated by Django 4.2.30 on 2026-05-15 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraWorkingDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('start_time', models.TimeField(verbose_name='Начало работы')),
                ('end_time', models.TimeField(verbose_name='Конец работы')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_days', to='masters.master')),
            ],
            options={
                'verbose_name': 'Дополнительный рабочий день',
                'verbose_name_plural': 'Дополнительные рабочие дни',
                'unique_together': {('master', 'date')},
            },
        ),
        migrations.CreateModel(
            name='ExtraWorkingDayBreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(verbose_name='Начало перерыва')),
                ('end_time', models.TimeField(verbose_name='Конец перерыва')),
                ('extra_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breaks', to='masters.extraworkingday')),
            ],
            options={
                'verbose_name': 'Перерыв (доп. день)',
                'verbose_name_plural': 'Перерывы (доп. дни)',
            },
        ),
    ]
