# Generated by Django 4.2.30 on 2026-06-05 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='address',
            field=models.CharField(blank=True, help_text='Где вы принимаете клиентов', max_length=255, verbose_name='Адрес мастера'),
        ),
    ]
