# Generated by Django 4.2.30 on 2026-07-26 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_master_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='max_link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка на профиль MAX'),
        ),
        migrations.AddField(
            model_name='master',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Telegram @username'),
        ),
        migrations.AddField(
            model_name='master',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер WhatsApp'),
        ),
    ]
