# Generated by Django 4.2.30 on 2026-05-17 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_extraworkingday_extraworkingdaybreak'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='master',
            name='slug',
        ),
        migrations.AddField(
            model_name='master',
            name='login',
            field=models.CharField(blank=True, help_text='Оставьте пустым, чтобы ссылка была с ID', max_length=50, null=True, unique=True, verbose_name='Логин (для ссылки)'),
        ),
    ]
