# Generated by Django 4.2.30 on 2026-07-27 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0003_master_max_link_master_telegram_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='confirmed_by_master',
            field=models.BooleanField(default=False, verbose_name='Подтверждено мастером'),
        ),
    ]
