# Generated by Django 4.2.30 on 2026-05-22 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0004_alter_service_duration_servicecategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Аватар'),
        ),
    ]
