# Generated by Django 4.2.30 on 2026-05-25 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0005_master_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlacklistedClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('reason', models.TextField(blank=True, verbose_name='Причина блокировки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blacklisted_clients', to='masters.master')),
            ],
            options={
                'verbose_name': 'Клиент в чёрном списке',
                'verbose_name_plural': 'Чёрный список клиентов',
                'unique_together': {('master', 'phone')},
            },
        ),
    ]
