# Generated by Django 4.2.30 on 2026-05-25 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0006_blacklistedclient'),
    ]

    operations = [
        migrations.AddField(
            model_name='blacklistedclient',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Имя'),
        ),
    ]
