# Generated by Django 4.2.30 on 2026-05-25 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('masters', '0007_blacklistedclient_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('new_booking', 'Новая запись'), ('cancelled_booking', 'Отмена записи'), ('changed_booking', 'Изменение записи'), ('system', 'Системное'), ('promo', 'Реклама/Акция'), ('warning', 'Предупреждение')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='masters.master')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
