# Generated by Django 4.2.30 on 2026-05-25 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0008_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='created_by',
            field=models.CharField(choices=[('client', 'Клиент'), ('master', 'Мастер')], default='client', max_length=10, verbose_name='Кто создал'),
        ),
    ]
