# Generated by Django 4.2.30 on 2026-05-31 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0010_supportmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='client_address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Адрес клиента'),
        ),
        migrations.AddField(
            model_name='booking',
            name='is_travel',
            field=models.BooleanField(default=False, verbose_name='Выезд к клиенту'),
        ),
        migrations.AddField(
            model_name='booking',
            name='travel_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Стоимость выезда'),
        ),
        migrations.AddField(
            model_name='booking',
            name='travel_time',
            field=models.IntegerField(default=0, verbose_name='Время на дорогу (минут)'),
        ),
        migrations.AddField(
            model_name='master',
            name='profile_type',
            field=models.CharField(choices=[('home', '🏠 Домашний (клиенты приходят)'), ('travel', '🚗 Выездной (езжу к клиентам)'), ('hybrid', '🔄 Гибрид (оба варианта)')], default='home', max_length=10, verbose_name='Тип работы'),
        ),
        migrations.AddField(
            model_name='master',
            name='travel_address_from',
            field=models.CharField(blank=True, help_text='Откуда выезжаю (город, улица)', max_length=255, verbose_name='Мой обычный адрес старта'),
        ),
        migrations.AddField(
            model_name='master',
            name='travel_price_default',
            field=models.DecimalField(decimal_places=2, default=0, help_text='0 - бесплатно', max_digits=8, verbose_name='Стоимость выезда (₽)'),
        ),
        migrations.AddField(
            model_name='master',
            name='travel_time_default',
            field=models.IntegerField(default=30, help_text='Будет добавляться между выездными записями', verbose_name='Время на дорогу по умолчанию (минут)'),
        ),
    ]
