# Generated by Django 4.2.30 on 2026-05-31 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0011_booking_client_address_booking_is_travel_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='master',
            old_name='travel_price_default',
            new_name='travel_price',
        ),
        migrations.RemoveField(
            model_name='master',
            name='travel_time_default',
        ),
        migrations.AddField(
            model_name='master',
            name='travel_time',
            field=models.IntegerField(default=30, help_text='Будет добавляться после каждой выездной записи', verbose_name='Время на дорогу (минут)'),
        ),
        migrations.AlterField(
            model_name='master',
            name='profile_type',
            field=models.CharField(choices=[('home', '🏠 Домашний (клиенты приходят)'), ('travel', '🚗 Выездной (езжу к клиентам)')], default='home', max_length=10, verbose_name='Тип работы'),
        ),
        migrations.AlterField(
            model_name='master',
            name='travel_address_from',
            field=models.CharField(blank=True, help_text='Например: Москва, ул. Тверская', max_length=255, verbose_name='Мой адрес (откуда выезжаю)'),
        ),
    ]
