# Generated by Django 4.2.30 on 2026-05-31 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0012_rename_travel_price_default_master_travel_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='profile_type',
            field=models.CharField(choices=[('home', '🏠 Домашний (клиенты приходят)'), ('travel', '🚗 Выездной (езжу к клиентам)')], default='home', max_length=10),
        ),
    ]
