# Generated by Django 4.2.30 on 2026-05-31 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0013_service_profile_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='profile_type',
            field=models.CharField(choices=[('home', '🏠 Домашний (клиенты приходят)'), ('travel', '🚗 Выездной (езжу к клиентам)')], default='home', max_length=10),
        ),
        migrations.AddField(
            model_name='schedule',
            name='profile_type',
            field=models.CharField(choices=[('home', '🏠 Домашний (клиенты приходят)'), ('travel', '🚗 Выездной (езжу к клиентам)')], default='home', max_length=10),
        ),
    ]
