# Generated by Django 4.2.30 on 2026-05-31 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0014_booking_profile_type_schedule_profile_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayoff',
            name='profile_type',
            field=models.CharField(default='home', max_length=10, verbose_name='Тип профиля'),
        ),
        migrations.AddField(
            model_name='extraworkingday',
            name='profile_type',
            field=models.CharField(default='home', max_length=10, verbose_name='Тип профиля'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='profile_type',
            field=models.CharField(default='home', max_length=10, verbose_name='Тип профиля'),
        ),
    ]
